--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Fevereiro-24-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIAL
--------------------------------------------------------

  CREATE TABLE "MATERIAL" 
   (	"ID" NUMBER, 
	"LAMINATION" CHAR(2 BYTE), 
	"TREATMENT" CHAR(2 BYTE), 
	"THICKNESS" NUMBER(10,2), 
	"WIDTH" NUMBER(10,2), 
	"LENGTH" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIAL_STANDARD
--------------------------------------------------------

  CREATE TABLE "MATERIAL_STANDARD" 
   (	"MATERIAL_ID" NUMBER, 
	"STANDARD_ID" NUMBER, 
	"ACCEPT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PURCHASE_ORDER
--------------------------------------------------------

  CREATE TABLE "PURCHASE_ORDER" 
   (	"ID" NUMBER, 
	"PURCHASE_PLANNING_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PURCHASE_ORDER_ITEM
--------------------------------------------------------

  CREATE TABLE "PURCHASE_ORDER_ITEM" 
   (	"ID" NUMBER, 
	"PURCHASE_ORDER_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"DATE" DATE, 
	"WEIGHT" NUMBER(10,2), 
	"PRICE" NUMBER(10,2), 
	"TAX" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PURCHASE_PLANNING
--------------------------------------------------------

  CREATE TABLE "PURCHASE_PLANNING" 
   (	"ID" NUMBER, 
	"QUOTATION_ID" NUMBER, 
	"DATE" DATE, 
	"OWNER" VARCHAR2(50 BYTE), 
	"APPROVE_DATE" DATE, 
	"APPROVE_USER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  CREATE TABLE "PURCHASE_PLANNING_ITEM" 
   (	"ID" NUMBER, 
	"PLANNING_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"DATE" DATE, 
	"WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUOTATION
--------------------------------------------------------

  CREATE TABLE "QUOTATION" 
   (	"ID" NUMBER, 
	"DATE" DATE, 
	"CREATOR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUOTATION_ITEM
--------------------------------------------------------

  CREATE TABLE "QUOTATION_ITEM" 
   (	"ID" NUMBER, 
	"QUOTATION_ID" NUMBER, 
	"LAMINATION" VARCHAR2(2 BYTE), 
	"TREATMENT" VARCHAR2(2 BYTE), 
	"THICKNESS" NUMBER(10,2), 
	"STANDARD" NUMBER, 
	"WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  CREATE TABLE "QUOTATION_ITEM_QUOTE" 
   (	"ID" NUMBER, 
	"QUOTATION_ITEM_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"WEIGHT" NUMBER(10,2), 
	"PRICE" NUMBER(10,2), 
	"STANDARD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUOTATION_REQUEST
--------------------------------------------------------

  CREATE TABLE "QUOTATION_REQUEST" 
   (	"ID" NUMBER, 
	"QUOTATION_ID" NUMBER, 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUEST
--------------------------------------------------------

  CREATE TABLE "REQUEST" 
   (	"ID" NUMBER, 
	"DATE" DATE, 
	"CREATOR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUEST_ITEM
--------------------------------------------------------

  CREATE TABLE "REQUEST_ITEM" 
   (	"ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"DATE" DATE, 
	"WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Table STANDARD
--------------------------------------------------------

  CREATE TABLE "STANDARD" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "SUPPLIER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER_IN_STOCK
--------------------------------------------------------

  CREATE TABLE "SUPPLIER_IN_STOCK" 
   (	"ID" NUMBER, 
	"QUOTATION_ITEM_QUOTE_ID" NUMBER, 
	"WIDTH" NUMBER(10,2), 
	"LENGTH" NUMBER(10,2), 
	"WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER_STANDARD
--------------------------------------------------------

  CREATE TABLE "SUPPLIER_STANDARD" 
   (	"SUPPLIER_ID" NUMBER, 
	"STANDARD_ID" NUMBER, 
	"AVAILABLE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATERIAL_PK" ON "MATERIAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index MATERIAL_STANDARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATERIAL_STANDARD_PK" ON "MATERIAL_STANDARD" ("MATERIAL_ID", "STANDARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_ORDER_PK" ON "PURCHASE_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_ORDER_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_ORDER_ITEM_PK" ON "PURCHASE_ORDER_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_PLANNING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_PLANNING_PK" ON "PURCHASE_PLANNING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_PLANNING_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_PLANNING_ITEM_PK" ON "PURCHASE_PLANNING_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUOTATION_PK" ON "QUOTATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUOTATION_ITEM_PK" ON "QUOTATION_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_ITEM_QUOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUOTATION_ITEM_QUOTE_PK" ON "QUOTATION_ITEM_QUOTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUOTATION_REQUEST_PK" ON "QUOTATION_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REQUEST_PK" ON "REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUEST_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REQUEST_ITEM_PK" ON "REQUEST_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index STARDARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARDARD_PK" ON "STANDARD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STARDARD_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STARDARD_UK1" ON "STANDARD" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUPPLIER_PK" ON "SUPPLIER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUPPLIER_UK1" ON "SUPPLIER" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_IN_STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUPPLIER_IN_STOCK_PK" ON "SUPPLIER_IN_STOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_STANDARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUPPLIER_STANDARD_PK" ON "SUPPLIER_STANDARD" ("SUPPLIER_ID", "STANDARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MATERIAL
--------------------------------------------------------
  
  ALTER TABLE "MATERIAL" ADD CONSTRAINT "MATERIAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATERIAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIAL_STANDARD
--------------------------------------------------------

  ALTER TABLE "MATERIAL_STANDARD" ADD CONSTRAINT "MATERIAL_STANDARD_PK" PRIMARY KEY ("MATERIAL_ID", "STANDARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATERIAL_STANDARD" MODIFY ("ACCEPT" NOT NULL ENABLE);
  ALTER TABLE "MATERIAL_STANDARD" MODIFY ("STANDARD_ID" NOT NULL ENABLE);
  ALTER TABLE "MATERIAL_STANDARD" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("PURCHASE_PLANNING_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASE_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PURCHASE_ORDER_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("PURCHASE_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASE_PLANNING
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING" ADD CONSTRAINT "PURCHASE_PLANNING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUOTATION
--------------------------------------------------------

  ALTER TABLE "QUOTATION" ADD CONSTRAINT "QUOTATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "QUOTATION" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUOTATION_ITEM
--------------------------------------------------------

  ALTER TABLE "QUOTATION_ITEM" ADD CONSTRAINT "QUOTATION_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("STANDARD" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("THICKNESS" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("TREATMENT" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("LAMINATION" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  ALTER TABLE "QUOTATION_ITEM_QUOTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM_QUOTE" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM_QUOTE" MODIFY ("STANDARD" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM_QUOTE" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM_QUOTE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table QUOTATION_REQUEST
--------------------------------------------------------

  ALTER TABLE "QUOTATION_REQUEST" ADD CONSTRAINT "QUOTATION_REQUEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "QUOTATION_REQUEST" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_REQUEST" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "REQUEST" ADD CONSTRAINT "REQUEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REQUEST" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "REQUEST" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "REQUEST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUEST_ITEM
--------------------------------------------------------

  ALTER TABLE "REQUEST_ITEM" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_ITEM" ADD CONSTRAINT "REQUEST_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REQUEST_ITEM" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_ITEM" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_ITEM" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_ITEM" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table STANDARD
--------------------------------------------------------

  ALTER TABLE "STANDARD" ADD CONSTRAINT "STANDARD_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "STANDARD" ADD CONSTRAINT "STANDARD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "STANDARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "STANDARD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPPLIER" ADD CONSTRAINT "SUPPLIER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPPLIER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER_IN_STOCK
--------------------------------------------------------

  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" ADD CONSTRAINT "SUPPLIER_IN_STOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("WIDTH" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("QUOTATION_ITEM_QUOTE_ID" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER_STANDARD
--------------------------------------------------------

  ALTER TABLE "SUPPLIER_STANDARD" ADD CONSTRAINT "SUPPLIER_STANDARD_PK" PRIMARY KEY ("SUPPLIER_ID", "STANDARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPPLIER_STANDARD" MODIFY ("AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_STANDARD" MODIFY ("STANDARD_ID" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_STANDARD" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MATERIAL_STANDARD
--------------------------------------------------------

  ALTER TABLE "MATERIAL_STANDARD" ADD CONSTRAINT "MATERIAL_STANDARD_FK1" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("ID") ENABLE;
  ALTER TABLE "MATERIAL_STANDARD" ADD CONSTRAINT "MATERIAL_STANDARD_FK2" FOREIGN KEY ("STANDARD_ID")
	  REFERENCES "STANDARD" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PURCHASE_FK1" FOREIGN KEY ("PURCHASE_PLANNING_ID")
	  REFERENCES "PURCHASE_PLANNING" ("ID") ENABLE;
  ALTER TABLE "PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PURCHASE_FK2" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "SUPPLIER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PURCHASE_ORDER_ITEM_FK1" FOREIGN KEY ("PURCHASE_ORDER_ID")
	  REFERENCES "PURCHASE_ORDER" ("ID") ENABLE;
  ALTER TABLE "PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PURCHASE_ORDER_ITEM_FK2" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_PLANNING
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING" ADD CONSTRAINT "PURCHASE_PLANNING_FK1" FOREIGN KEY ("QUOTATION_ID")
	  REFERENCES "QUOTATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK1" FOREIGN KEY ("PLANNING_ID")
	  REFERENCES "PURCHASE_PLANNING" ("ID") ENABLE;
  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK2" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("ID") ENABLE;
  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK3" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "SUPPLIER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_ITEM
--------------------------------------------------------

  ALTER TABLE "QUOTATION_ITEM" ADD CONSTRAINT "QUOTATION_ITEM_FK1" FOREIGN KEY ("QUOTATION_ID")
	  REFERENCES "QUOTATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  ALTER TABLE "QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK1" FOREIGN KEY ("QUOTATION_ITEM_ID")
	  REFERENCES "QUOTATION_ITEM" ("ID") ENABLE;
  ALTER TABLE "QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK2" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "SUPPLIER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_REQUEST
--------------------------------------------------------

  ALTER TABLE "QUOTATION_REQUEST" ADD CONSTRAINT "QUOTATION_REQUEST_FK1" FOREIGN KEY ("QUOTATION_ID")
	  REFERENCES "QUOTATION" ("ID") ENABLE;
  ALTER TABLE "QUOTATION_REQUEST" ADD CONSTRAINT "QUOTATION_REQUEST_FK2" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "REQUEST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST_ITEM
--------------------------------------------------------

  ALTER TABLE "REQUEST_ITEM" ADD CONSTRAINT "REQUEST_ITEM_FK1" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "REQUEST" ("ID") ENABLE;
  ALTER TABLE "REQUEST_ITEM" ADD CONSTRAINT "REQUEST_ITEM_FK2" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SUPPLIER_IN_STOCK
--------------------------------------------------------

  ALTER TABLE "SUPPLIER_IN_STOCK" ADD CONSTRAINT "SUPPLIER_IN_STOCK_FK1" FOREIGN KEY ("QUOTATION_ITEM_QUOTE_ID")
	  REFERENCES "QUOTATION_ITEM_QUOTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPPLIER_STANDARD
--------------------------------------------------------

  ALTER TABLE "SUPPLIER_STANDARD" ADD CONSTRAINT "SUPPLIER_STANDARD_FK1" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "SUPPLIER" ("ID") ENABLE;
  ALTER TABLE "SUPPLIER_STANDARD" ADD CONSTRAINT "SUPPLIER_STANDARD_FK2" FOREIGN KEY ("STANDARD_ID")
	  REFERENCES "STANDARD" ("ID") ENABLE;

