--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIAL_STANDARD
--------------------------------------------------------

  CREATE TABLE "MATERIAL_STANDARD" 
   (	"MATERIAL_ID" NUMBER, 
	"STANDARD_ID" NUMBER, 
	"STANDARD_ACCEPT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIAL_STANDARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATERIAL_STANDARD_PK" ON "MATERIAL_STANDARD" ("MATERIAL_ID", "STANDARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MATERIAL_STANDARD
--------------------------------------------------------

  ALTER TABLE "MATERIAL_STANDARD" ADD CONSTRAINT "MATERIAL_STANDARD_PK" PRIMARY KEY ("MATERIAL_ID", "STANDARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MATERIAL_STANDARD" MODIFY ("STANDARD_ACCEPT" NOT NULL ENABLE);
  ALTER TABLE "MATERIAL_STANDARD" MODIFY ("STANDARD_ID" NOT NULL ENABLE);
  ALTER TABLE "MATERIAL_STANDARD" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MATERIAL_STANDARD
--------------------------------------------------------

  ALTER TABLE "MATERIAL_STANDARD" ADD CONSTRAINT "MATERIAL_STANDARD_FK1" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("MATERIAL_ID") ENABLE;
  ALTER TABLE "MATERIAL_STANDARD" ADD CONSTRAINT "MATERIAL_STANDARD_FK2" FOREIGN KEY ("STANDARD_ID")
	  REFERENCES "STANDARD" ("STANDARD_ID") ENABLE;
