--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  CREATE TABLE "PURCHASE_PLANNING_ITEM" 
   (	"PLANNING_ITEM_ID" NUMBER, 
	"PLANNING_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"PLANNING_DATE" DATE, 
	"PLANNING_WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_PLANNING_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_PLANNING_ITEM_PK" ON "PURCHASE_PLANNING_ITEM" ("PLANNING_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_PK" PRIMARY KEY ("PLANNING_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK1" FOREIGN KEY ("PLANNING_ID")
	  REFERENCES "PURCHASE_PLANNING" ("PLANNING_ID") ENABLE;
  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK2" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("MATERIAL_ID") ENABLE;
  ALTER TABLE "PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK3" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "SUPPLIER" ("SUPPLIER_ID") ENABLE;
