--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PURCHASE_ORDER_ITEM
--------------------------------------------------------

  CREATE TABLE "PURCHASE_ORDER_ITEM" 
   (	"PURCHASE_ORDER_ITEM_ID" NUMBER, 
	"PURCHASE_ORDER_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"PURCHASE_ORDER_ITEM_DATE" DATE, 
	"PURCHASE_ORDER_ITEM_WEIGHT" NUMBER(10,2), 
	"PURCHASE_ORDER_ITEM_UNIT_PRICE" NUMBER(10,2), 
	"PURCHASE_ORDER_ITEM_TAX" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_ORDER_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_ORDER_ITEM_PK" ON "PURCHASE_ORDER_ITEM" ("PURCHASE_ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PURCHASE_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PURCHASE_ORDER_ITEM_PK" PRIMARY KEY ("PURCHASE_ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("PURCHASE_ORDER_ITEM_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("PURCHASE_ORDER_ITEM_DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("PURCHASE_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER_ITEM" MODIFY ("PURCHASE_ORDER_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PURCHASE_ORDER_ITEM_FK1" FOREIGN KEY ("PURCHASE_ORDER_ID")
	  REFERENCES "PURCHASE_ORDER" ("PURCHASE_ORDER_ID") ENABLE;
  ALTER TABLE "PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PURCHASE_ORDER_ITEM_FK2" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "MATERIAL" ("MATERIAL_ID") ENABLE;
