--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PURCHASE_ORDER
--------------------------------------------------------

  CREATE TABLE "PURCHASE_ORDER" 
   (	"PURCHASE_ORDER_ID" NUMBER, 
	"PURCHASE_PLANNING_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"PURCHASE_ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_ORDER_PK" ON "PURCHASE_ORDER" ("PURCHASE_ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PK" PRIMARY KEY ("PURCHASE_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("PURCHASE_ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("PURCHASE_PLANNING_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_ORDER" MODIFY ("PURCHASE_ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PURCHASE_FK1" FOREIGN KEY ("PURCHASE_PLANNING_ID")
	  REFERENCES "PURCHASE_PLANNING" ("PLANNING_ID") ENABLE;
  ALTER TABLE "PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PURCHASE_FK2" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "SUPPLIER" ("SUPPLIER_ID") ENABLE;
