--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PURCHASE_PLANNING
--------------------------------------------------------

  CREATE TABLE "PURCHASE_PLANNING" 
   (	"PLANNING_ID" NUMBER, 
	"QUOTATION_ID" NUMBER, 
	"PLANNING_DATE" DATE, 
	"PLANNING_OWNER" VARCHAR2(50 BYTE), 
	"PLANNING_APPROVE_DATE" DATE, 
	"PLANNING_APPROVE_USER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_PLANNING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PURCHASE_PLANNING_PK" ON "PURCHASE_PLANNING" ("PLANNING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PURCHASE_PLANNING
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING" ADD CONSTRAINT "PURCHASE_PLANNING_PK" PRIMARY KEY ("PLANNING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("PLANNING_OWNER" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("PLANNING_DATE" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "PURCHASE_PLANNING" MODIFY ("PLANNING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_PLANNING
--------------------------------------------------------

  ALTER TABLE "PURCHASE_PLANNING" ADD CONSTRAINT "PURCHASE_PLANNING_FK1" FOREIGN KEY ("QUOTATION_ID")
	  REFERENCES "QUOTATION" ("QUOTATION_ID") ENABLE;
