--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Fevereiro-10-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  CREATE TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" 
   (	"QUOTATION_ITEM_QUOTE_ID" NUMBER, 
	"QUOTATION_ITEM_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"QUOTE_STANDARD" NUMBER, 
	"QUOTE_WEIGHT" NUMBER(10,2), 
	"QUOTE_PRICE" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_ITEM_QUOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE_PK" ON "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" ("QUOTATION_ITEM_QUOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTATION_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_PK" PRIMARY KEY ("QUOTATION_ITEM_QUOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTE_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTE_STANDARD" NOT NULL ENABLE);
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTATION_ITEM_QUOTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK1" FOREIGN KEY ("QUOTATION_ITEM_ID")
	  REFERENCES "ALTAMIRA_BPM"."QUOTATION_ITEM" ("QUOTATION_ITEM_ID") ENABLE;
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK2" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "ALTAMIRA_BPM"."SUPPLIER" ("SUPPLIER_ID") ENABLE;
  ALTER TABLE "ALTAMIRA_BPM"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK3" FOREIGN KEY ("QUOTATION_ITEM_QUOTE_ID")
	  REFERENCES "ALTAMIRA_BPM"."STANDARD" ("STANDARD_ID") ENABLE;
