--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUOTATION_REQUEST
--------------------------------------------------------

  CREATE TABLE "QUOTATION_REQUEST" 
   (	"QUOTATION_REQUEST_ID" NUMBER, 
	"QUOTATION_ID" NUMBER, 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUOTATION_REQUEST_PK" ON "QUOTATION_REQUEST" ("QUOTATION_REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QUOTATION_REQUEST
--------------------------------------------------------

  ALTER TABLE "QUOTATION_REQUEST" ADD CONSTRAINT "QUOTATION_REQUEST_PK" PRIMARY KEY ("QUOTATION_REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "QUOTATION_REQUEST" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_REQUEST" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "QUOTATION_REQUEST" MODIFY ("QUOTATION_REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_REQUEST
--------------------------------------------------------

  ALTER TABLE "QUOTATION_REQUEST" ADD CONSTRAINT "QUOTATION_REQUEST_FK1" FOREIGN KEY ("QUOTATION_ID")
	  REFERENCES "QUOTATION" ("QUOTATION_ID") ENABLE;
  ALTER TABLE "QUOTATION_REQUEST" ADD CONSTRAINT "QUOTATION_REQUEST_FK2" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "REQUEST" ("REQUEST_ID") ENABLE;
