--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUPPLIER_IN_STOCK
--------------------------------------------------------

  CREATE TABLE "SUPPLIER_IN_STOCK" 
   (	"SUPPLIER_STOCK_ID" NUMBER, 
	"QUOTATION_ITEM_ID" NUMBER, 
	"MATERIAL_WIDTH" NUMBER(10,2), 
	"MATERIAL_LENGTH" NUMBER(10,2), 
	"SUPPLIER_WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_IN_STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUPPLIER_IN_STOCK_PK" ON "SUPPLIER_IN_STOCK" ("SUPPLIER_STOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIER_IN_STOCK
--------------------------------------------------------

  ALTER TABLE "SUPPLIER_IN_STOCK" ADD CONSTRAINT "SUPPLIER_IN_STOCK_PK" PRIMARY KEY ("SUPPLIER_STOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("SUPPLIER_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("MATERIAL_WIDTH" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("QUOTATION_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SUPPLIER_IN_STOCK" MODIFY ("SUPPLIER_STOCK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUPPLIER_IN_STOCK
--------------------------------------------------------

  ALTER TABLE "SUPPLIER_IN_STOCK" ADD CONSTRAINT "SUPPLIER_IN_STOCK_FK1" FOREIGN KEY ("QUOTATION_ITEM_ID")
	  REFERENCES "QUOTATION_ITEM" ("QUOTATION_ITEM_ID") ENABLE;
