DECLARE

SUPPLIER_ID_1 NUMBER := 1;
SUPPLIER_ID_2 NUMBER := 2;
SUPPLIER_ID_3 NUMBER := 3;
SUPPLIER_ID_4 NUMBER := 4;
SUPPLIER_ID_5 NUMBER := 5;
SUPPLIER_ID_6 NUMBER := 6;

SUPPLIER_CONTACT_ID_1 NUMBER := 1;
SUPPLIER_CONTACT_ID_2 NUMBER := 2;
SUPPLIER_CONTACT_ID_3 NUMBER := 3;
SUPPLIER_CONTACT_ID_4 NUMBER := 4;
SUPPLIER_CONTACT_ID_5 NUMBER := 5;
SUPPLIER_CONTACT_ID_6 NUMBER := 6;

BEGIN

---------------------------
-- INSERT SUPPLIER CONTACTS
---------------------------
       
INSERT INTO SUPPLIER_CONTACT (ID, NAME, MAIL_ADDRESS)
       VALUES (SUPPLIER_CONTACT_ID_1,'USIMINAS','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (ID, NAME, MAIL_ADDRESS)
       VALUES (SUPPLIER_CONTACT_ID_2,'LEALFER','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (ID, NAME, MAIL_ADDRESS)
       VALUES (SUPPLIER_CONTACT_ID_3,'MULTIAÇOS','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (ID, NAME, MAIL_ADDRESS)
       VALUES (SUPPLIER_CONTACT_ID_4,'MBA','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (ID, NAME, MAIL_ADDRESS)
       VALUES (SUPPLIER_CONTACT_ID_5,'KLOEKNER','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (ID, NAME, MAIL_ADDRESS)
       VALUES (SUPPLIER_CONTACT_ID_6,'ACOFER','tests.nfe@altamiral.com.br');

-------------------
-- INSERT SUPPLIERS
-------------------
INSERT INTO SUPPLIER (ID, NAME, SUPPLIER_CONTACT_ID)
       VALUES (SUPPLIER_ID_1,'USIMINAS',SUPPLIER_CONTACT_ID_1);
       
INSERT INTO SUPPLIER (ID, NAME, SUPPLIER_CONTACT_ID)
       VALUES (SUPPLIER_ID_2,'LEALFER',SUPPLIER_CONTACT_ID_2);
       
INSERT INTO SUPPLIER (ID, NAME, SUPPLIER_CONTACT_ID)
       VALUES (SUPPLIER_ID_3,'MULTIAÇOS',SUPPLIER_CONTACT_ID_3);
       
INSERT INTO SUPPLIER (ID, NAME, SUPPLIER_CONTACT_ID)
       VALUES (SUPPLIER_ID_4,'MBA',SUPPLIER_CONTACT_ID_4);
       
INSERT INTO SUPPLIER (ID, NAME, SUPPLIER_CONTACT_ID)
       VALUES (SUPPLIER_ID_5,'KLOEKNER',SUPPLIER_CONTACT_ID_5);
       
INSERT INTO SUPPLIER (ID, NAME, SUPPLIER_CONTACT_ID)
       VALUES (SUPPLIER_ID_6,'ACOFER',SUPPLIER_CONTACT_ID_6);
       
END;
