--------------------------------------------------------
--  File created - Friday-March-28-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure CREATE_PURCHASE_PLANNING
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HEAD_USER_DB"."CREATE_PURCHASE_PLANNING" (P_PLANNING_ID OUT NUMBER, P_QUOTATION_ID IN NUMBER) AS

BEGIN

  -- INSERT A NEW PURCHASE PLANNING IF NOT EXISTS FOR GIVEN P_QUOTATION_ID
  INSERT INTO PURCHASE_PLANNING (ID, QUOTATION_ID, CREATED_DATE, CREATOR_NAME, APPROVE_DATE, APPROVE_USER)
  SELECT PURCHASE_PLANNING_SEQUENCE.NEXTVAL, P_QUOTATION_ID, SYSDATE, 'Alessandro', NULL, NULL
  FROM DUAL
  WHERE NOT EXISTS ( 
    SELECT 1 FROM PURCHASE_PLANNING
    WHERE QUOTATION_ID = P_QUOTATION_ID);

  -- GET PURCHASE PLANNING ID FOR THE GIVEN QUOTATION_ID
  SELECT P.ID
  INTO P_PLANNING_ID 
  FROM PURCHASE_PLANNING P 
  WHERE P.QUOTATION_ID = P_QUOTATION_ID;
  
  -- MERGE PURCHASE PLANNING ITEMS
  MERGE INTO PURCHASE_PLANNING_ITEM PPI
  USING
  (SELECT RI.ID AS REQUEST_ITEM_ID,
          QIQ.SUPPLIER_ID,
          RI.ARRIVAL_DATE AS "DATE",
          0 AS WEIGHT
   FROM QUOTATION_REQUEST QR,
        REQUEST_ITEM RI,
        MATERIAL M,
        QUOTATION_ITEM QI, 
        QUOTATION_ITEM_QUOTE QIQ     
   WHERE QR.QUOTATION_ID = '1' AND
         RI.REQUEST_ID = QR.REQUEST_ID AND
         RI.MATERIAL_ID = M.ID AND
         QIQ.QUOTATION_ITEM_ID = QI.ID AND
         QI.LAMINATION = M.LAMINATION AND 
         QI.TREATMENT = M.TREATMENT AND 
         QI.THICKNESS = M.THICKNESS AND 
         QI.QUOTATION_ID = QR.QUOTATION_ID AND
         QIQ.PRICE = (SELECT MIN(QIQ2.PRICE) FROM QUOTATION_ITEM_QUOTE QIQ2 WHERE QIQ2.QUOTATION_ITEM_ID = QI.ID)) R1
  ON
    (PPI.PLANNING_ID = P_PLANNING_ID AND
    PPI.REQUEST_ITEM_ID = R1.REQUEST_ITEM_ID)
    
  WHEN MATCHED THEN
  UPDATE SET PPI.SUPPLIER_ID = PPI.SUPPLIER_ID
  
  WHEN NOT MATCHED THEN
  INSERT VALUES(PLANNING_ITEM_SEQUENCE.NEXTVAL, P_PLANNING_ID, R1.REQUEST_ITEM_ID, R1.SUPPLIER_ID, R1."DATE", R1.WEIGHT);

END CREATE_PURCHASE_PLANNING;

/
