--------------------------------------------------------
--  File created - Tuesday-April-08-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure CREATE_QUOTATION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HEAD_USER_DB"."CREATE_QUOTATION" (P_QUOTATION_ID OUT NUMBER) AS
  
BEGIN
  
   -- INSERT A NEW QUOTATION IF NOT EXISTS AN OPEN QUOTATION (CLOSED_DATE IS NULL)
  INSERT INTO QUOTATION
  SELECT
    QUOTATION_SEQUENCE.NEXTVAL, 
    SYSDATE, 
    'Alessandro', 
    NULL 
  FROM DUAL
  WHERE NOT EXISTS ( 
    SELECT 1 FROM QUOTATION
    WHERE CLOSED_DATE IS NULL);
  
  -- GET ID OF THE OPEN QUOTATION
  SELECT Q.ID 
  INTO P_QUOTATION_ID 
  FROM QUOTATION Q 
  WHERE ROWID = (SELECT MAX(ROWID) FROM QUOTATION WHERE CLOSED_DATE IS NULL);
  
  MERGE INTO QUOTATION_ITEM QI
  USING 
  (SELECT M.LAMINATION, M.TREATMENT, M.THICKNESS, SUM(RI.WEIGHT) AS WEIGHT
  FROM 
    REQUEST R 
    INNER JOIN REQUEST_ITEM RI ON R.ID = RI.REQUEST_ID
    INNER JOIN MATERIAL M ON RI.MATERIAL_ID = M.ID
    WHERE NOT EXISTS (SELECT 1 FROM QUOTATION_REQUEST QR WHERE QR.REQUEST_ID = R.ID)
    GROUP BY M.LAMINATION, M.TREATMENT, M.THICKNESS) R1
  ON
    (QI.QUOTATION_ID = P_QUOTATION_ID AND
    QI.LAMINATION = R1.LAMINATION AND 
    QI.TREATMENT = R1.TREATMENT AND
    QI.THICKNESS = R1.THICKNESS)
  WHEN MATCHED THEN
  UPDATE SET QI.WEIGHT = QI.WEIGHT + R1.WEIGHT
  WHEN NOT MATCHED THEN
  INSERT VALUES (QUOTATION_ITEM_SEQUENCE.NEXTVAL, P_QUOTATION_ID, R1.LAMINATION, R1.TREATMENT, R1.THICKNESS, 1, R1.WEIGHT);

  INSERT INTO QUOTATION_ITEM_QUOTE
   SELECT QUOTATION_ITEM_QUOTE_SEQUENCE.NEXTVAL, RES.* FROM (SELECT DISTINCT QI.ID AS QUOTATION_ID, S.ID AS SUPPLIER_ID, 0, SPL.PRICE, ' '
  FROM 
    SUPPLIER S 
    INNER JOIN SUPPLIER_PRICE_LIST SPL ON S.ID = SPL.SUPPLIER_ID
    INNER JOIN MATERIAL M ON SPL.MATERIAL_ID = M.ID
    INNER JOIN REQUEST_ITEM RI ON M.ID = RI.MATERIAL_ID
    INNER JOIN REQUEST R ON RI.REQUEST_ID = R.ID
    INNER JOIN QUOTATION_ITEM QI ON QI.LAMINATION = M.LAMINATION AND QI.TREATMENT = M.TREATMENT AND QI.THICKNESS = M.THICKNESS
  WHERE 
    QI.QUOTATION_ID = P_QUOTATION_ID AND
    --NOT EXISTS (SELECT 1 FROM QUOTATION_REQUEST QR WHERE QR.REQUEST_ID = R.ID);
    NOT EXISTS (SELECT 1 FROM QUOTATION_ITEM_QUOTE QIQ WHERE QIQ.QUOTATION_ITEM_ID = QI.ID))RES;

  INSERT INTO QUOTATION_REQUEST
  SELECT QUOTATION_REQUEST_SEQUENCE.NEXTVAL, P_QUOTATION_ID, R.ID
  FROM REQUEST R
  WHERE 
    NOT EXISTS (SELECT 1 FROM QUOTATION_REQUEST QR WHERE QR.REQUEST_ID = R.ID) AND
    EXISTS (SELECT 1 FROM REQUEST_ITEM RI WHERE RI.REQUEST_ID = R.ID);
    
END CREATE_QUOTATION;

/
