--------------------------------------------------------
--  File created - Wednesday-February-19-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MATERIAL
--------------------------------------------------------

  CREATE TABLE "PARTH1"."MATERIAL" 
   (	"MATERIAL_ID" NUMBER, 
	"MATERIAL_CODE" VARCHAR2(20 BYTE), 
	"MATERIAL_LAMINATION" CHAR(2 BYTE), 
	"MATERIAL_TREATMENT" CHAR(2 BYTE), 
	"MATERIAL_THICKNESS" NUMBER(10,2), 
	"MATERIAL_WIDTH" NUMBER(10,2), 
	"MATERIAL_LENGTH" NUMBER(10,2), 
	"MATERIAL_DESCRIPTION" VARCHAR2(100 BYTE), 
	"MATERIAL_TAX" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."MATERIAL_PK" ON "PARTH1"."MATERIAL" ("MATERIAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIAL_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."MATERIAL_UK1" ON "PARTH1"."MATERIAL" ("MATERIAL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MATERIAL
--------------------------------------------------------

  ALTER TABLE "PARTH1"."MATERIAL" ADD CONSTRAINT "MATERIAL_UK1" UNIQUE ("MATERIAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."MATERIAL" ADD CONSTRAINT "MATERIAL_PK" PRIMARY KEY ("MATERIAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."MATERIAL" MODIFY ("MATERIAL_WIDTH" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."MATERIAL" MODIFY ("MATERIAL_THICKNESS" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."MATERIAL" MODIFY ("MATERIAL_TREATMENT" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."MATERIAL" MODIFY ("MATERIAL_LAMINATION" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."MATERIAL" MODIFY ("MATERIAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."MATERIAL" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
