INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-01';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-02';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-03';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-04';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-05';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-06';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-07';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-08';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-09';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-10';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-11';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-12';

INSERT INTO MATERIAL_STANDARD (MATERIAL_ID, STANDARD_ID, STANDARD_ACCEPT)
SELECT M.MATERIAL_ID, '1', 'Y' FROM MATERIAL M WHERE M.MATERIAL_CODE = 'TEST-13';