INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-01', 'FQ', 'PR', '2.65', '500', null, 'BOBINA FQ PRETA ASTM570G45 2,65MM X 500MM', '19.58');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.NEXTVAL, 'TEST-02', 'FQ', 'PR', '2', '100', NULL, 'BOB. F.Q./PRETA ASTM-570G45 2,00MM X 100MM', '18.45');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.NEXTVAL, 'TEST-03', 'FQ', 'PR', '2', '200', NULL, 'BOB.F.Q/PRETA ASTM-570G45-2,00MMX200MM', '17.65');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-04', 'FQ', 'PR', '2', '240', null, 'BOB.FQ/PRETA ASTM-570G45-2,00MMX240MM', '15.54');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-05', 'FQ', 'PR', '2', '330', null, 'BOBINA F.Q. PRETA ASTM570 G45 2,00MMX330MM', '16.69');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-06', 'FQ', 'PR', '2', '400', null, 'BOBINA F.Q.PRETA ASTM570 G45 2,00MM X400MM_x000D', '17.25');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-07', 'FQ', 'PR', '1.8', '85', null, 'BOBINA F.Q.PRETA ASTM570G45 1,80MM X 85MM', '18.69');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-08', 'FQ', 'PR', '1.8', '240', null, 'BOBINA F.Q.PRETAASTM570G45 1,80MM X 240MM', '17.65');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-09', 'FQ', 'PR', '1.5', '85', null, 'ROLO FQ PRETA USICIVIL300 1,50MM X 85MM', '16.6');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-10', 'FF', 'GA', '0.85', '100', null, 'BOBINA F.F. SAE 1008/1010 - 0,85 MM X 100MM', '15.5');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.NEXTVAL, 'TEST-11', 'FF', 'GA', '0.85', '990', NULL, 'BOBINA F.F. SAE 1008/1010 - 0,85 MM X 990MM', '16.5');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.NEXTVAL, 'TEST-12', 'FF', 'GA', '0.6', '915', NULL, 'BOBINA F.F.SAE 1008 -  0.60MM X 915MM', '17.5');
            
INSERT INTO MATERIAL (MATERIAL_ID, MATERIAL_CODE, MATERIAL_LAMINATION, MATERIAL_TREATMENT, MATERIAL_THICKNESS, MATERIAL_WIDTH, MATERIAL_LENGTH, MATERIAL_DESCRIPTION, MATERIAL_TAX)
            VALUES(MATERIAL_SEQUENCE.nextval, 'TEST-13', 'FF', 'GA', '0.75', '1200', '2000', 'CHAPA F.F.SAE 1008 0,75MM X 1200MM X 2000MM', '18');