--------------------------------------------------------
--  File created - Wednesday-February-19-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  CREATE TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" 
   (	"PLANNING_ITEM_ID" NUMBER, 
	"PLANNING_ID" NUMBER, 
	"REQUEST_ITEM_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_PLANNING_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."PURCHASE_PLANNING_ITEM_PK" ON "PARTH1"."PURCHASE_PLANNING_ITEM" ("PLANNING_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_PK" PRIMARY KEY ("PLANNING_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" MODIFY ("SUPPLIER_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" MODIFY ("REQUEST_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" MODIFY ("PLANNING_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_PLANNING_ITEM
--------------------------------------------------------

  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK1" FOREIGN KEY ("PLANNING_ID")
	  REFERENCES "PARTH1"."PURCHASE_PLANNING" ("PLANNING_ID") ENABLE;
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK2" FOREIGN KEY ("REQUEST_ITEM_ID")
	  REFERENCES "PARTH1"."REQUEST_ITEM" ("REQUEST_ITEM_ID") ENABLE;
  ALTER TABLE "PARTH1"."PURCHASE_PLANNING_ITEM" ADD CONSTRAINT "PURCHASE_PLANNING_ITEM_FK3" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "PARTH1"."SUPPLIER" ("SUPPLIER_ID") ENABLE;
