--------------------------------------------------------
--  File created - Wednesday-February-19-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUOTATION
--------------------------------------------------------

  CREATE TABLE "PARTH1"."QUOTATION" 
   (	"QUOTATION_ID" NUMBER, 
	"QUOTATION_DATE" DATE, 
	"QUOTATION_CREATOR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."QUOTATION_PK" ON "PARTH1"."QUOTATION" ("QUOTATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QUOTATION
--------------------------------------------------------

  ALTER TABLE "PARTH1"."QUOTATION" ADD CONSTRAINT "QUOTATION_PK" PRIMARY KEY ("QUOTATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."QUOTATION" MODIFY ("QUOTATION_CREATOR" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION" MODIFY ("QUOTATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
