--------------------------------------------------------
--  File created - Wednesday-February-19-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  CREATE TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" 
   (	"QUOTATION_ITEM_QUOTE_ID" NUMBER, 
	"QUOTATION_ITEM_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_WEIGHT" NUMBER(10,2), 
	"SUPPLIER_PRICE" NUMBER(10,2), 
	"SUPPLIER_STANDARD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_ITEM_QUOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."QUOTATION_ITEM_QUOTE_PK" ON "PARTH1"."QUOTATION_ITEM_QUOTE" ("QUOTATION_ITEM_QUOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_ITEM_QUOTE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."QUOTATION_ITEM_QUOTE_UK1" ON "PARTH1"."QUOTATION_ITEM_QUOTE" ("QUOTATION_ITEM_ID", "SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_UK1" UNIQUE ("QUOTATION_ITEM_ID", "SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_PK" PRIMARY KEY ("QUOTATION_ITEM_QUOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" MODIFY ("SUPPLIER_STANDARD" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" MODIFY ("SUPPLIER_PRICE" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" MODIFY ("SUPPLIER_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTATION_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" MODIFY ("QUOTATION_ITEM_QUOTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_ITEM_QUOTE
--------------------------------------------------------

  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK1" FOREIGN KEY ("QUOTATION_ITEM_ID")
	  REFERENCES "PARTH1"."QUOTATION_ITEM" ("QUOTATION_ITEM_ID") ENABLE;
  ALTER TABLE "PARTH1"."QUOTATION_ITEM_QUOTE" ADD CONSTRAINT "QUOTATION_ITEM_QUOTE_FK2" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "PARTH1"."SUPPLIER" ("SUPPLIER_ID") ENABLE;
