--------------------------------------------------------
--  File created - Wednesday-February-19-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUOTATION_ITEM
--------------------------------------------------------

  CREATE TABLE "PARTH1"."QUOTATION_ITEM" 
   (	"QUOTATION_ITEM_ID" NUMBER, 
	"QUOTATION_ID" NUMBER, 
	"MATERIAL_LAMINATION" VARCHAR2(2 BYTE), 
	"MATERIAL_TREATMENT" VARCHAR2(2 BYTE), 
	"MATERIAL_THICKNESS" NUMBER(10,2), 
	"MATERIAL_STANDARD" NUMBER, 
	"REQUEST_WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUOTATION_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."QUOTATION_ITEM_PK" ON "PARTH1"."QUOTATION_ITEM" ("QUOTATION_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QUOTATION_ITEM
--------------------------------------------------------

  ALTER TABLE "PARTH1"."QUOTATION_ITEM" ADD CONSTRAINT "QUOTATION_ITEM_PK" PRIMARY KEY ("QUOTATION_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."QUOTATION_ITEM" MODIFY ("MATERIAL_STANDARD" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM" MODIFY ("MATERIAL_THICKNESS" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM" MODIFY ("MATERIAL_TREATMENT" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM" MODIFY ("MATERIAL_LAMINATION" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM" MODIFY ("QUOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."QUOTATION_ITEM" MODIFY ("QUOTATION_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table QUOTATION_ITEM
--------------------------------------------------------

  ALTER TABLE "PARTH1"."QUOTATION_ITEM" ADD CONSTRAINT "QUOTATION_ITEM_FK1" FOREIGN KEY ("QUOTATION_ID")
	  REFERENCES "PARTH1"."QUOTATION" ("QUOTATION_ID") ENABLE;
