DECLARE

V_REQUEST_ID_1 NUMBER := 73;
V_REQUEST_ID_2 NUMBER := 74;
V_MATERIAL_1 NUMBER := 1;
V_MATERIAL_2 NUMBER := 2;
V_MATERIAL_3 NUMBER := 3;
V_MATERIAL_4 NUMBER := 4;
V_MATERIAL_5 NUMBER := 5;
V_MATERIAL_6 NUMBER := 6;
V_MATERIAL_7 NUMBER := 7;
V_MATERIAL_8 NUMBER := 8;
V_MATERIAL_9 NUMBER := 9;
V_MATERIAL_10 NUMBER := 10;
V_MATERIAL_11 NUMBER := 11;
V_MATERIAL_12 NUMBER := 12;
V_MATERIAL_13 NUMBER := 13;

BEGIN

-- Request Id - 73

INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL ,V_REQUEST_ID_1, V_MATERIAL_1, TO_DATE('09/01/2014','dd/mm/yyyy') ,'10506.96');
              
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL ,V_REQUEST_ID_1, V_MATERIAL_2, TO_DATE('09/01/2014','dd/mm/yyyy') ,'7661.858');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.nextval , V_REQUEST_ID_1, V_MATERIAL_2, TO_DATE('17/01/2014','dd/mm/yyyy') ,'7760.442');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.nextval , V_REQUEST_ID_1, V_MATERIAL_3, TO_DATE('09/01/2014','dd/mm/yyyy') ,'1808.508');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.nextval , V_REQUEST_ID_1, V_MATERIAL_4, TO_DATE('17/12/2013','dd/mm/yyyy') ,'5274.843');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_5, TO_DATE('13/12/2013','dd/mm/yyyy') ,'12951.156');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_5, TO_DATE('17/12/2013','dd/mm/yyyy') ,'13566.615');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_5, TO_DATE('07/01/2014','dd/mm/yyyy') ,'13159.56');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_5, TO_DATE('14/01/2014','dd/mm/yyyy') ,'13381.56');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_6, TO_DATE('16/12/2013','dd/mm/yyyy') ,'5988.672');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_6, TO_DATE('08/01/2014','dd/mm/yyyy') ,'6873.649');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_1, V_MATERIAL_7, TO_DATE('06/01/2014','dd/mm/yyyy') ,'10346.876');
    
-- Request Id - 74

INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_2, V_MATERIAL_8, TO_DATE('16/12/2013','dd/mm/yyyy') ,'6806.641');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_2, V_MATERIAL_9, TO_DATE('15/01/2014','dd/mm/yyyy') ,'7705.77');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_2, V_MATERIAL_10, TO_DATE('16/12/2013','dd/mm/yyyy') ,'10228.579');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_2, V_MATERIAL_11, TO_DATE('13/12/2013','dd/mm/yyyy') ,'2067.98');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_2, V_MATERIAL_12, TO_DATE('13/12/2013','dd/mm/yyyy') ,'5535.169');
       
INSERT INTO REQUEST_ITEM (REQUEST_ITEM_ID, REQUEST_ID, MATERIAL_ID, REQUEST_DATE, REQUEST_WEIGHT)
       VALUES (REQUEST_ITEM_SEQUENCE.NEXTVAL , V_REQUEST_ID_2, V_MATERIAL_13, TO_DATE('08/01/2014','dd/mm/yyyy') ,'1278.324');
       
END;