--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REQUEST_ITEM
--------------------------------------------------------

  CREATE TABLE "PARTH1"."REQUEST_ITEM" 
   (	"REQUEST_ITEM_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"REQUEST_DATE" DATE, 
	"REQUEST_WEIGHT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUEST_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."REQUEST_ITEM_PK" ON "PARTH1"."REQUEST_ITEM" ("REQUEST_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REQUEST_ITEM
--------------------------------------------------------

  ALTER TABLE "PARTH1"."REQUEST_ITEM" ADD CONSTRAINT "REQUEST_ITEM_PK" PRIMARY KEY ("REQUEST_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."REQUEST_ITEM" MODIFY ("REQUEST_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."REQUEST_ITEM" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."REQUEST_ITEM" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."REQUEST_ITEM" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."REQUEST_ITEM" MODIFY ("REQUEST_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REQUEST_ITEM
--------------------------------------------------------

  ALTER TABLE "PARTH1"."REQUEST_ITEM" ADD CONSTRAINT "REQUEST_ITEM_FK1" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "PARTH1"."REQUEST" ("REQUEST_ID") ENABLE;
  ALTER TABLE "PARTH1"."REQUEST_ITEM" ADD CONSTRAINT "REQUEST_ITEM_FK2" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "PARTH1"."MATERIAL" ("MATERIAL_ID") ENABLE;
