INSERT INTO SUPPLIER_STANDARD (SUPPLIER_ID, STANDARD_ID, STANDARD_AVAILABLE)
       VALUES ('1','1','Y');
       
INSERT INTO SUPPLIER_STANDARD (SUPPLIER_ID, STANDARD_ID, STANDARD_AVAILABLE)
       VALUES ('2','1','Y');
       
INSERT INTO SUPPLIER_STANDARD (SUPPLIER_ID, STANDARD_ID, STANDARD_AVAILABLE)
       VALUES ('3','1','Y');
       
INSERT INTO SUPPLIER_STANDARD (SUPPLIER_ID, STANDARD_ID, STANDARD_AVAILABLE)
       VALUES ('4','1','Y');
       
INSERT INTO SUPPLIER_STANDARD (SUPPLIER_ID, STANDARD_ID, STANDARD_AVAILABLE)
       VALUES ('5','1','Y');
       
INSERT INTO SUPPLIER_STANDARD (SUPPLIER_ID, STANDARD_ID, STANDARD_AVAILABLE)
       VALUES ('6','1','Y');