---------------------------
-- INSERT SUPPLIER CONTACTS
---------------------------
       
INSERT INTO SUPPLIER_CONTACT (SUPPLIER_CONTACT_ID, CONTACT_NAME, MAIL_ADDRESS)
       VALUES ('1','USIMINAS','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (SUPPLIER_CONTACT_ID, CONTACT_NAME, MAIL_ADDRESS)
       VALUES ('2','LEALFER','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (SUPPLIER_CONTACT_ID, CONTACT_NAME, MAIL_ADDRESS)
       VALUES ('3','MULTIAÇOS','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (SUPPLIER_CONTACT_ID, CONTACT_NAME, MAIL_ADDRESS)
       VALUES ('4','MBA','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (SUPPLIER_CONTACT_ID, CONTACT_NAME, MAIL_ADDRESS)
       VALUES ('5','KLOEKNER','tests.nfe@altamiral.com.br');
       
INSERT INTO SUPPLIER_CONTACT (SUPPLIER_CONTACT_ID, CONTACT_NAME, MAIL_ADDRESS)
       VALUES ('6','ACOFER','tests.nfe@altamiral.com.br');

-------------------
-- INSERT SUPPLIERS
-------------------
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_CONTACT_ID)
       VALUES ('1','USIMINAS','1');
       
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_CONTACT_ID)
       VALUES ('2','LEALFER','2');
       
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_CONTACT_ID)
       VALUES ('3','MULTIAÇOS','3');
       
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_CONTACT_ID)
       VALUES ('4','MBA','4');
       
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_CONTACT_ID)
       VALUES ('5','KLOEKNER','5');
       
INSERT INTO SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_CONTACT_ID)
       VALUES ('6','ACOFER','6');