--------------------------------------------------------
--  File created - Thursday-January-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUPPLIER_STANDARD
--------------------------------------------------------

  CREATE TABLE "PARTH1"."SUPPLIER_STANDARD" 
   (	"SUPPLIER_ID" NUMBER, 
	"STANDARD_ID" NUMBER, 
	"STANDARD_AVAILABLE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLIER_STANDARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTH1"."SUPPLIER_STANDARD_PK" ON "PARTH1"."SUPPLIER_STANDARD" ("SUPPLIER_ID", "STANDARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIER_STANDARD
--------------------------------------------------------

  ALTER TABLE "PARTH1"."SUPPLIER_STANDARD" ADD CONSTRAINT "SUPPLIER_STANDARD_PK" PRIMARY KEY ("SUPPLIER_ID", "STANDARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PARTH1"."SUPPLIER_STANDARD" MODIFY ("STANDARD_AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."SUPPLIER_STANDARD" MODIFY ("STANDARD_ID" NOT NULL ENABLE);
  ALTER TABLE "PARTH1"."SUPPLIER_STANDARD" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SUPPLIER_STANDARD
--------------------------------------------------------

  ALTER TABLE "PARTH1"."SUPPLIER_STANDARD" ADD CONSTRAINT "SUPPLIER_STANDARD_FK1" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "PARTH1"."SUPPLIER" ("SUPPLIER_ID") ENABLE;
  ALTER TABLE "PARTH1"."SUPPLIER_STANDARD" ADD CONSTRAINT "SUPPLIER_STANDARD_FK2" FOREIGN KEY ("STANDARD_ID")
	  REFERENCES "PARTH1"."STANDARD" ("STANDARD_ID") ENABLE;
